server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://192.168.19.1:5432/issue-ticketing-db
    username: user
    password: secret-pass#123
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans
